#!/bin/bash
docker compose down
docker image rm vistaextractor-bay vistaextractor-tam vistaextractor-wpb vistaextractor-v08 vistaextractor-vx130

sudo rm -rf bay
sudo rm -rf tam
sudo rm -rf wpb
sudo rm -rf v08
sudo rm -rf vx130

mkdir -p bay/code bay/db/rou bay/jrn/jrn bay/jrn/alt bay/sys
mkdir -p tam/code tam/db/rou tam/jrn/jrn tam/jrn/alt tam/sys
mkdir -p wpb/code wpb/db/rou wpb/jrn/jrn wpb/jrn/alt wpb/sys
mkdir -p v08/code v08/db/v08/bay/rou v08/db/v08/tam/rou v08/db/v08/wpb/rou v08/jrn/jrn v08/jrn/alt v08/sys
mkdir -p vx130/code vx130/db/vx130/vx130code vx130/db/vx130/vx130data vx130/jrn/jrn vx130/jrn/alt vx130/sys

docker run -v $(pwd)/bay/code:/code -v $(pwd)/bay/sys:/irissys -v $(pwd)/bay/db:/irisdb -v $(pwd)/bay/jrn:/irisjrn --name bay -d intersystems/irishealth:2023.2.0.201.0
docker run -v $(pwd)/tam/code:/code -v $(pwd)/tam/sys:/irissys -v $(pwd)/tam/db:/irisdb -v $(pwd)/tam/jrn:/irisjrn --name tam -d intersystems/irishealth:2023.2.0.201.0
docker run -v $(pwd)/wpb/code:/code -v $(pwd)/wpb/sys:/irissys -v $(pwd)/wpb/db:/irisdb -v $(pwd)/wpb/jrn:/irisjrn --name wpb -d intersystems/irishealth:2023.2.0.201.0
docker run -v $(pwd)/v08/code:/code -v $(pwd)/v08/sys:/irissys -v $(pwd)/v08/db:/irisdb -v $(pwd)/v08/jrn:/irisjrn --name v08 -d intersystems/irishealth:2023.2.0.201.0
docker run -v $(pwd)/vx130/code:/code -v $(pwd)/vx130/sys:/irissys -v $(pwd)/vx130/db:/irisdb -v $(pwd)/vx130/jrn:/irisjrn --name vx130 -d intersystems/irishealth:2023.2.0.201.0
sleep 20

docker exec -it --user root bay chown -R irisowner:irisowner /irisdb /irisjrn /irissys /code
docker exec -it --user root tam chown -R irisowner:irisowner /irisdb /irisjrn /irissys /code
docker exec -it --user root wpb chown -R irisowner:irisowner /irisdb /irisjrn /irissys /code
docker exec -it --user root v08 chown -R irisowner:irisowner /irisdb /irisjrn /irissys /code
docker exec -it --user root vx130 chown -R irisowner:irisowner /irisdb /irisjrn /irissys /code

docker cp vistaInstaller.cls bay:/code/
docker cp vistaInstaller.cls tam:/code/
docker cp vistaInstaller.cls wpb:/code/
docker cp v08Installer.cls v08:/code/
docker cp vx130Installer.cls vx130:/code/
docker cp src vx130:/code/

docker stop bay
docker stop tam
docker stop wpb
docker stop v08
docker stop vx130

docker rm bay
docker rm tam
docker rm wpb
docker rm v08
docker rm vx130






