#!/bin/bash
docker exec -it vx130 iris session iris -U vx130 "##class(%SYSTEM.OBJ).LoadDir(\"/code/src/\",\"cku\",,1)"


docker exec -it v08 iris session iris -U vx130 "##class(VX130.IRISInstance).Init()"
docker exec -it v08 iris session iris -U vx130 "##class(VX130.VistaSite).Init()"
docker exec -it v08 iris session iris -U vx130 "##class(VX130.GlobalsToWatch).Init()"
docker exec -it v08 iris session iris -U vx130 "##class(VX130Task.AddJournalFileTask).ScheduleEveryMinute()"
docker exec -it v08 iris session iris -U vx130 "##class(VX130Task.JournalReaderTask).ScheduleEveryMinute()"

docker exec -it v08 iris session iris -U vx130 "##class(VX130.JournalReaderStatus).Init()"