version: '3.9'
services:
  web:
    image: intersystems/webgateway:2021.1.3.389.0
    environment:
      - ISC_DATA_DIRECTORY=/webconf
    volumes:
      - ./web:/webconf
    ports:
      - 80:80
    container_name: web
    hostname: web
  bay:
    build: .
    volumes:
      - baysys:/irissys
      #- baydb:/irisdb
      #- bayjrn:/irisjrn
    environment:
      - ISC_DATA_DIRECTORY=/irissys
      - VX130_STA3N=516
    ports:
      - 30516:52773
    container_name: bay
    hostname: bay
  tam:
    build: .
    volumes:
      - tamsys:/irissys
      - tamdb:/irisdb
      - tamjrn:/irisjrn
    environment:
      - ISC_DATA_DIRECTORY=/irissys
      - VX130_STA3N=673
    ports:
      - 30673:52773
    container_name: tam
    hostname: tam
  wpb:
    build: .
    volumes:
      - wpbsys:/irissys
      - wpbdb:/irisdb
      - wpbjrn:/irisjrn
    environment:
      - ISC_DATA_DIRECTORY=/irissys
      - VX130_STA3N=548
    ports:
      - 30548:52773
    container_name: wpb
    hostname: wpb
volumes:
  baysys:
  baydb:
  bayjrn:
  tamsys:
  tamdb:
  tamjrn:
  wpbsys:
  wpbdb:
  wpbjrn: