version: '3.9'
services:
  web:
    image: intersystems/webgateway:2023.1.0.207.0
    environment:
      - ISC_DATA_DIRECTORY=/webconf
    volumes:
      - ./web:/webconf
    ports:
      - 80:80
    container_name: web
    hostname: web
  bay:
    build: .
    volumes:
      - ./bay/sys:/irissys
      - ./bay/db:/irisdb
      - ./bay/jrn:/irisjrn
      - ./bay/code:/code
    environment:
      - ISC_DATA_DIRECTORY=/irissys
      - VISTA_SITE=516
    container_name: bay
    hostname: bay
  tam:
    build: .
    volumes:
      - ./tam/sys:/irissys
      - ./tam/db:/irisdb
      - ./tam/jrn:/irisjrn
      - ./tam/code:/code
    environment:
      - ISC_DATA_DIRECTORY=/irissys
      - VISTA_SITE=673
    container_name: tam
    hostname: tam
  wpb:
    build: .
    volumes:
      - ./wpb/sys:/irissys
      - ./wpb/db:/irisdb
      - ./wpb/jrn:/irisjrn
      - ./wpb/code:/code
    environment:
      - ISC_DATA_DIRECTORY=/irissys
      - VISTA_SITE=548
    container_name: wpb
    hostname: wpb
  v08:
    build: .
    volumes:
      - ./v08/sys:/irissys
      - ./v08/db:/irisdb
      - ./v08/jrn:/irisjrn
      - ./v08/code:/code
    environment:
      - ISC_DATA_DIRECTORY=/irissys
      - IRIS_INSTANCE=V08
    container_name: v08
    hostname: v08
  vx130:
    build: .
    volumes:
      - ./vx130/sys:/irissys
      - ./vx130/db:/irisdb
      - ./vx130/jrn:/irisjrn
      - ./vx130/code:/code
    environment:
      - ISC_DATA_DIRECTORY=/irissys
      - IRIS_INSTANCE=VX130
    container_name: vx130
    hostname: vx130
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./apis:/apis
    environment:
      - SWAGGER_JSON=/apis/cb.json 
    ports:
      - 8080:8080
    container_name: swagger
    hostname: swagger
