version: '3.9'
services:
  web:
    image: container.intersystems.com/intersystems/webgateway:2024.1
    environment:
      - ISC_DATA_DIRECTORY=/webconf
    volumes:
      - ./web:/webconf
    ports:
      - 80:80
    container_name: web
    hostname: web
  bay:
    build: .
    volumes:
      - ./bay/sys:/irissys
      - ./bay/db:/irisdb
      - ./bay/jrn:/irisjrn
      - ./bay/code:/code
    environment:
      - ISC_DATA_DIRECTORY=/irissys
      - VISTA_SITE=516
    container_name: bay
    hostname: bay
  tam:
    build: .
    volumes:
      - ./tam/sys:/irissys
      - ./tam/db:/irisdb
      - ./tam/jrn:/irisjrn
      - ./tam/code:/code
    environment:
      - ISC_DATA_DIRECTORY=/irissys
      - VISTA_SITE=673
    container_name: tam
    hostname: tam
  wpb:
    build: .
    volumes:
      - ./wpb/sys:/irissys
      - ./wpb/db:/irisdb
      - ./wpb/jrn:/irisjrn
      - ./wpb/code:/code
    environment:
      - ISC_DATA_DIRECTORY=/irissys
      - VISTA_SITE=548
    container_name: wpb
    hostname: wpb
  v08:
    build: .
    volumes:
      - ./v08/sys:/irissys
      - ./v08/db:/irisdb
      - ./v08/jrn:/irisjrn
      - ./v08/code:/code
    environment:
      - ISC_DATA_DIRECTORY=/irissys
      - IRIS_INSTANCE=V08
    container_name: v08
    hostname: v08
  flr:
    build: .
    volumes:
      - ./flr/sys:/irissys
      - ./flr/jrn:/irisjrn
      - ./flr/code:/code
    environment:
      - ISC_DATA_DIRECTORY=/irissys
      - IRIS_INSTANCE=flr
    container_name: flr
    hostname: flr
  fdw:
    build: .
    volumes:
      - ./fdw/sys:/irissys
      - ./fdw/db:/irisdb
      - ./fdw/jrn:/irisjrn
      - ./fdw/code:/code
    environment:
      - ISC_DATA_DIRECTORY=/irissys
      - IRIS_INSTANCE=fdw
    container_name: fdw
    hostname: fdw
  classbuilder:
    image: classbuilder
    ports:
      - 8080:80
    container_name: classbuilder
    hostname: classbuilder