version: '3.9'
services:
  web:
    image: intersystems/webgateway:2021.1.3.389.0
    environment:
      - ISC_DATA_DIRECTORY=/webconf
    volumes:
      - ./web:/webconf
    ports:
      - 80:80
    container_name: web
    hostname: web
  bay:
    build: .
    volumes:
      - baysys:/irissys
      - baydb:/irisdb
      - bayjrn:/irisjrn
    environment:
      - ISC_DATA_DIRECTORY=/irissys
      - VX130_STA3N=516
    container_name: bay
    hostname: bay
  tam:
    build: .
    volumes:
      - tamsys:/irissys
      - tamdb:/irisdb
      - tamjrn:/irisjrn
    environment:
      - ISC_DATA_DIRECTORY=/irissys
      - VX130_STA3N=673
    container_name: tam
    hostname: tam
  wpb:
    build: .
    volumes:
      - wpbsys:/irissys
      - wpbdb:/irisdb
      - wpbjrn:/irisjrn
    environment:
      - ISC_DATA_DIRECTORY=/irissys
      - VX130_STA3N=548
    container_name: wpb
    hostname: wpb
  v08:
    build: .
    volumes:
      - v08sys:/irissys
      - v08db:/irisdb
      - v08jrn:/irisjrn
    environment:
      - ISC_DATA_DIRECTORY=/irissys
      - IRIS_INSTANCE=V08
    container_name: v08
    hostname: v08
  vx130:
    build: .
    volumes:
      - vx130sys:/irissys
      - vx130db:/irisdb
      - vx130jrn:/irisjrn
    environment:
      - ISC_DATA_DIRECTORY=/irissys
      - IRIS_INSTANCE=VX130
    container_name: vx130
    hostname: vx130
volumes:
  baysys:
  baydb:
  bayjrn:
  tamsys:
  tamdb:
  tamjrn:
  wpbsys:
  wpbdb:
  wpbjrn:
  v08sys:
  v08db:
  v08jrn:
  vx130sys:
  vx130db:
  vx130jrn: